### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by MatusOllah** [mappu/miqt#100]
Hello,
I'm trying to implement translations in my project.
I see that miqt has methods for translating like `QTranslator_Tr` but I'm not sure how to generate the `.ts` files required for translation and how to properly integrate them into my project.

How do I translate properly in miqt?
Any examples or detailed instructions would be greatly appreciated!

**Comment by mappu** [comment]
Thanks for your patience. There's not yet an easy answer.

In Qt C++ the process is:
1. Mark strings with `tr("something")`
    - It's a static class method, so that your C++ class name can be part of the "context" of the translation
2. Use `lupdate` to scan source code and extract .ts files
3. Translate .ts files with Qt Linguist
4. Add `TRANSLATIONS += file.ts` in the qmake .pro file.

In MIQT several steps will have to work differently:
1. Mark strings with `qt.QApplication_Tr("something")` or any other class version
    - Some short wrapper function would be really helpful 
2. Extract strings using some other extractor, probably [some xgettext implementation to .po format](https://github.com/gosexy/gettext)
3. Translate .po files with PoEdit
4. Convert .po files to .ts with `lconvert`
5. Use `lrelease` to pack .ts source to .qm binary file
6. Embed .qm binary file using either qrc/rcc process or singular go:embed process
7. Load the qm file at runtime: `translator := qt.NewQTranslator()`, `translator.load("file.qm")`, `qt.QCoreApplication_installTranslator(translator)`

This is not a good experience so it may be easier to stay within some pure-Go translation ecosystem. Only the downside is the qm translation system must be used to translate Qt system text (e.g. "OK"/"Cancel" buttons within default dialogs)

**Comment by MatusOllah** [comment]
Alright, tried embedding the translations files using `miqt-rcc` and loading them using `QCoreApplication_InstallTranslator`, but it didn't work as expected. I think I'll stick with a pure Go i18n package instead.
Closing this issue as resolved for now.

Here’s my code for reference in case you find it helpful:
```go
package main

import (
	"log/slog"
	"os"
	"runtime"

	_ "github.com/MatusOllah/gcharted/assets"
	_ "github.com/MatusOllah/gcharted/i18n"
	"github.com/MatusOllah/gcharted/internal/gui"
	"github.com/MatusOllah/slogcolor"
	qt "github.com/mappu/miqt/qt6"
)

func main() {
	// Logger
	slog.SetDefault(slog.New(slogcolor.NewHandler(os.Stderr, slogcolor.DefaultOptions)))

	slog.Info("GCharted version " + Version)
	slog.Info("Go version " + runtime.Version())
	slog.Info("Qt version " + qt.QLibraryInfo_Version().ToString())

	// Qt Application
	slog.Info("initializing QApplication")
	qt.NewQApplication(os.Args)

	translator := qt.NewQTranslator()
	translator.Load(":/i18n/sk.qm")
	qt.QCoreApplication_InstallTranslator(translator)

	qt.QGuiApplication_SetApplicationDisplayName("GCharted")
	qt.QCoreApplication_SetApplicationName("GCharted")
	qt.QCoreApplication_SetApplicationVersion(Version)

	slog.Info("showing GUI")
	mw := gui.NewMainWindow()
	mw.Ui().Retranslate()
	mw.Ui().MainWindow.Show()

	slog.Info("executing QApplication")
	qt.QApplication_Exec()
}
```
