### ISSUE TITLE
Build error: "unknown type name '_Bool'" when using macOS

### ISSUE THREAD

**Issue by FalcoG** [mappu/miqt#102]
Hello,

When trying to run this with Qt5 on Apple Silicon (M1 SoC; ARM-based) it doesn't work out of the box.

It requires setting a flag as discussed here: https://github.com/ilius/ayandict/discussions/6#discussioncomment-11187308. This has been tested with the "helloworld" example (https://github.com/mappu/miqt/blob/master/examples/helloworld/main.go)

Does work: `$ export CGO_CXXFLAGS='-D_Bool=bool' && go run main.go`
Doesn't work: `$ go run main.go`

Same applies to _build_ instead of _run_.

Without the flag it will throw the following errors:
```
$ go run main.go
# github.com/mappu/miqt/qt
In file included from gen_qabstractanimation.cpp:15:
cgo-gcc-export-header-prolog:54:8: error: unknown type name '_Bool'
cgo-gcc-export-header-prolog:58:8: error: unknown type name '_Bool'
cgo-gcc-export-header-prolog:70:8: error: unknown type name '_Bool'
cgo-gcc-export-header-prolog:71:8: error: unknown type name '_Bool'
cgo-gcc-export-header-prolog:80:69: error: unknown type name '_Bool'
cgo-gcc-export-header-prolog:81:70: error: unknown type name '_Bool'
cgo-gcc-export-header-prolog:83:8: error: unknown type name '_Bool'
cgo-gcc-export-header-prolog:86:8: error: unknown type name '_Bool'
cgo-gcc-export-header-prolog:97:95: error: unknown type name '_Bool'
cgo-gcc-export-header-prolog:101:8: error: unknown type name '_Bool'
cgo-gcc-export-header-prolog:119:8: error: unknown type name '_Bool'
cgo-gcc-export-header-prolog:126:8: error: unknown type name '_Bool'
cgo-gcc-export-header-prolog:126:104: error: unknown type name '_Bool'
cgo-gcc-export-header-prolog:140:8: error: unknown type name '_Bool'
cgo-gcc-export-header-prolog:141:8: error: unknown type name '_Bool'
cgo-gcc-export-header-prolog:143:8: error: unknown type name '_Bool'
cgo-gcc-export-header-prolog:144:8: error: unknown type name '_Bool'
cgo-gcc-export-header-prolog:164:8: error: unknown type name '_Bool'
cgo-gcc-export-header-prolog:166:8: error: unknown type name '_Bool'
fatal error: too many errors emitted, stopping now [-ferror-limit=]
```

### Reproduction:

1. Be on macOS 15.1.1 with an Apple M1
2. `$ brew install qt@5`
3. Add the following exports to e.g. ~/.zshrc:
```
export LDFLAGS="-L/opt/homebrew/opt/qt@5/lib"
export CPPFLAGS="-I/opt/homebrew/opt/qt@5/include"
export PKG_CONFIG_PATH="/opt/homebrew/opt/qt@5/lib/pkgconfig"
```
4. Create a demo directory; `$ mkdir ~/miqt-test && cd ~/miqt-test`
5. `$ go mod init helloworld`
6. `$ go get github.com/mappu/miqt/qt@master`
7. Create main.go with the contents of https://github.com/mappu/miqt/blob/master/examples/helloworld/main.go
8. `$ go run main.go`

**Comment by mappu** [comment]
Thank you for the detailed report. I had only tried an older version of macOS, but it seems like this `-D_Bool=bool` is needed for all newer Clang versions I tried. It also affects Windows as well.

For now I'll add a note in the macOS build guide section of the README. But, a proper fix would be to understand why this is needed (maybe some std change?) and change MIQT's own `cflags.go` files to solve it automatically.

**Comment by FalcoG** [comment]
Interesting, so macOS would've worked fine before without the flag? And that would make it seem that it's not really an arm64 vs amd64 problem either.

Also the clang version I've tried it with:

```
$ clang --version
Apple clang version 16.0.0 (clang-1600.0.26.4)
Target: arm64-apple-darwin24.1.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

I might not be able to find a fix for this as it's all quite new to me, but if you need anything tested on macOS let me know.

**Comment by mappu** [comment]
@FalcoG I have a draft branch up at #103 that I think will remove the requirement to add `-D_Bool=bool` yourself. I'll test it on all platforms I have access to, but if you could also test it on macOS arm64, that would be appreciated,

**Comment by FalcoG** [comment]
@mappu nice! That seems to do the trick. On that branch it now runs without issues when omitting the flag.
