### ISSUE TITLE
Genbindings for Qt 6.7+ has error with qcomparehelpers.h

### ISSUE THREAD

**Issue by ddkwork** [mappu/miqt#112]
The introduction of this header file since version 6.7 has caused dump ast to fail
https://github.com/qt/qtbase/blob/dev/src%2Fcorelib%2Fglobal%2Fqcomparehelpers.h#L5-L5

**Comment by ddkwork** [comment]
Perhaps -DQCOMPAREHELPERS_H should be added after parsing each .pc file so that clang can't read the contents of the QCOMPAREHELPERS.h file, which should eliminate some of the bugs, I'm not sure what the correct solution should be.

To verify this I tried to run bindgen within several operating systems such as msys2, Windows11, github codespace, action ubuntu, archlinux, debian12, etc. I finally found out that it's a problem with the version of qt. The latest qt for debian is version 6.4.2, and I'm using it in theI installed debian inside VMware and tried it. I installed debian in VMware and the bindgen in the ci repository should also be running qt 6.4.2.

**Comment by rcalixte** [comment]
There are excludes in one of the config files. There are some other troublesome things about Qt 6.7 as well that require some refactoring (at least in my experience), but I've also found it easier to build on Qt 6.7 starting with the 6.4 cache. (It's a workaround for now.)

**Comment by ddkwork** [comment]
I'm compiling the last version of clang that worked properly https://github.com/ddkwork/qt6.9/actions/workflows/build.yml
All modules will be compiled statically except cua, I don't know how to build static libraries for android, can you pr support android static libraries when you come back from vacation with free time?

**Comment by rcalixte** [comment]
I don't know if there is a large appetite for static Qt libraries. Static bindings should be okay though there might be some appeal for dynamic bindings as well.

**Comment by ddkwork** [comment]
On Win11, dynamic bindings cannot be debugged inside Goland. Maybe I'm not doing it the right way. Also, can you post the link to the config file you mentioned? I'd like to check it out, in case it solves the problem, then I'd still like to use the dev version of qt, because from the commits as close as I can tell, they do a lot of Win11 theming adaptation and other work, and pretty much auto-adapt to the system theme only after 6.8. 6.9 commits have very little about Win11, dev versions have a lot.

**Comment by ddkwork** [comment]
6.8.1
https://github.com/ddkwork/miqt/actions/runs/12476156140/job/34820566068

**Comment by rcalixte** [comment]
> 6.8.1 https://github.com/ddkwork/miqt/actions/runs/12476156140/job/34820566068

It looks like you're missing the private headers. If Arch has these in the repositories, install them. If the headers aren't available in the repository, open an issue with the packagers.

**Comment by ddkwork** [comment]
thx,i will try

**Comment by ddkwork** [comment]
![image](https://github.com/user-attachments/assets/3136d02b-79d7-45a6-91de-bb61b2c3be59)
It seems necessary to check if the flag of the PC file contains the 6.8.1 directory?

**Comment by ddkwork** [comment]
![image](https://github.com/user-attachments/assets/e032a8f9-6d44-4eac-883e-679559666e6d)
It seems that pkg config did not handle 6.8.1 as the parent directory of the private directory. Let me print out the clang command first to see. If that's the case, it would be a waste of time to look at the source code of pkg config. So, I plan to force the version number as the parent directory of the header file in the bindgen code:- Ixxxxx/6.8.1 Do you think this is reasonable?

**Comment by mappu** [comment]
> On Win11, dynamic bindings cannot be debugged inside Goland. Maybe I'm not doing it the right way.

I'm not a goland user, but like https://github.com/mappu/miqt/discussions/107 , I think it should work OK.

What happens when you try it? Is there any error message?

I do think that the first time to debug will take another 10-20 minutes, because the build with `delve` uses some different compile flags.

---

> I've also found it easier to build on Qt 6.7 starting with the 6.4 cache

The benefit of building Miqt with Qt 6.4 headers, is that it can be used with any older (6.4) or newer (6.8/6.9) runtime library. Using the newer runtime library should be enough to give the new features (Windows 11 theming) even if old headers are used in the compile time.

It would be nice to generate bindings for new methods and classes. But, i think the only way to do things like this is some sort of separate git fork, or a git branch, or another subfolder "qt69", something like this.

---

> > Perhaps -DQCOMPAREHELPERS_H should be added after parsing each .pc file so that clang can't read the contents of the QCOMPAREHELPERS.h file, which should eliminate some of the bugs, I'm not sure what the correct solution should be.
>
> Do not include qcomparehelpers.h directly. Use qcompare.h instead.

One possible way to fix this is to exclude the `qcomparehelpers.h` inside `genbindings/config-libraries.go`. The 3rd argument is a function that can exclude such difficult files, it should return `false` for this difficult file.

**Comment by ddkwork** [comment]
I decided to copy a qt6.6 or qt6.4 folder to the bindgen directory, and store the qt6.9 libs externally, so that it's easier for cmake to compile dlls or other demos.
