### ISSUE TITLE
Illegal use of unsafe.Pointer to store cgo.Handle

### ISSUE THREAD

**Issue by DanielAdolfsson** [mappu/miqt#38]
I noticed you're using `unsafe.Pointer(uintptr(cgo.NewHandle(slot))`.

I recently ran into this issue myself, where I wanted to store a cgo.Handle into a unsafe.Pointer field.
The general consensus seem to be that it is *not* a legal use of unsafe.Pointer.

Relevant:
https://github.com/golang/go/issues/49633
https://github.com/golang/go/commit/d2f4c935f2e247dd9949094c8a4f3ab8df2ba3a0#diff-ffa0f0c347d78cbdf6478bbdfb43131be08b1db600aa9968430ac9424a6361ed

The suggestion is to instead pass the address of your cgo.Handle.
But since it's a callback, I suppose it needs to be properly pinned as well.

**Comment by DanielAdolfsson** [comment]
Maybe the `void *slot` parameters could instead be changed into `intptr_t`, that'd allow cgo.Handle to fit in there

**Comment by mappu** [comment]
Great catch, thank you. I agree an int type sounds better than double indirection. I'll make this change,
