### ISSUE TITLE
Support subclassing

### ISSUE THREAD

**Issue by mappu** [mappu/miqt#42]
Discussion from https://news.ycombinator.com/item?id=41785568 :

> > > Is it possible to extend/subclass an existing QWidget and customise it?
> > >
> > For e.g. PaintEvent() from pure Go code? Not yet, but I have some idea on how to make it possible.
> >
> > Until then, a nice feature of CGO is you can write one custom Qt subclass in a .cpp file in the same folder as your .go files. Your C++ will be compiled with `go build`, and you can use your custom class directly from Go/MIQT. So even if some advanced Qt feature is not in the binding, anything is still possible at least. I'll make an example about this.
>
> I contribute to NodeGui, Qt on Nodejs. It doesn't try to emulate the C++ API by allowing subclassing. Instead it exposes most methods on QWidget classes/subclasses which process QEvent objects (and their subclasses) in the form of events which you can subscribe to as an application. You can listen to signals and also QEvent related traffic in much the same way. So, if you want to subclass a QWidget to do your own custom rendering/painting, you would create an instance of QWidget and then listen to/hook into, the incoming requests to repaint. Qt sees a normal QWidget instance, but you can customise it do act like the subclass you desire. This avoids any attempt to do a real C++ subclass at runtime. Internally, NodeGui subclasses almost every QWidget (and more) to hook into them to allow this. This works far better than you might expect and saves a ton of complexity.

**Comment by mappu** [comment]
[QObject::InstallEventFilter](https://doc.qt.io/qt-6/qobject.html#installEventFilter) may be an alternative to subclassing.

**Comment by jamalsa** [comment]
I think we can follow therecipe/qt to expose most of qt methods. As an example to override `data` for QAbstractItemModel it has `ConnectData` which accept a go function which will be called from C++ side whenever `data` method is called. The downside is we need to generate C++ subclass for each Qt classes to handle this which will make the binding bigger and longer to compile.

**Comment by jamalsa** [comment]
Thanks @mappu, I do some test on Windows with Qt 6.5.3 building `examples/helloworld6` on my  i7-8665U CPU (5 years old CPU) and 16 GB RAM 

|                         | master | miqt-subclass | change |
| ---------------- | ------------- | ------------- | ------------- |
| first build time | 00:20:28  | 00:23:47  | 16.2%  |
| binary size  | 6.470 KB  | 12.444 KB  | 92.3%  |

So the binary size almost doubled, but I think it is acceptable trade off if we can subclass Qt class.

**Comment by mappu** [comment]
Subclassing support is now available in master. To use it, call OnPaintEvent or any other function. Check the [examples/subclass](https://github.com/mappu/miqt/blob/master/examples/subclass/main.go) for more details.

One thing may be surprising: the callback takes an extra first argument `super`, which can be used to call the base implementation.

Everything seems to work in my testing, but there may still be bugs, so please try it out and let's resolve any issues before a new release is tagged.

**Comment by jamalsa** [comment]
Can we override `data` method from `QAbstractItemModel`? I looked at the generated source but didn't find anything.

**Comment by mappu** [comment]
@jamalsa I checked this. It looks like QAbstractItemModel will still need some more work. I've raised #88.
