### ISSUE TITLE
NewIcon4(filename) silently fails for .SVG files

### ISSUE THREAD

**Issue by mark-summerfield** [mappu/miqt#62]
I have just started trying out miQt using Qt 6.4.2 on Debian.
I tried adding an application icon. When I use go-up.png it works fine; but when I use go-up.svg no icon appears.
```
package main

import (
	"fmt"
	"os"

	qt "github.com/mappu/miqt/qt6"
)

func main() {
	var counter int
	qt.NewQApplication(os.Args)

	window := qt.NewQWidget2()
	icon := qt.NewQIcon4("go-up.png")
	window.SetWindowIcon(icon)
	helloButton := qt.NewQPushButton3("Hello world!")
	aboutButton := qt.NewQPushButton3("About Qt")

	helloButton.OnPressed(func() {
		counter++
		helloButton.SetText(fmt.Sprintf(
			"You have clicked the button %d time(s)", counter))
	})
	aboutButton.OnPressed(func() { qt.QApplication_AboutQt() })

	box := qt.NewQHBoxLayout(window)
	box.AddWidget(helloButton.QWidget)
	box.AddWidget(aboutButton.QWidget)

	window.Show()
	qt.QApplication_Exec()
}
```
![go-up](https://github.com/user-attachments/assets/64853d65-b010-4770-99ca-60c325187ae4)
![go-up](https://github.com/user-attachments/assets/e84c3170-1928-44dc-b6fb-fb7149b648cc)

**Comment by mappu** [comment]
These icons are loaded using [Qt Image Format](https://doc.qt.io/qt-5/qtimageformats-index.html) plugins. Qt always supports an imageformat for PNG, but SVG support requires loading the SVG plugin.

I think this only requires linking with QtSvg in LDFLAGS. It may also require the imageformats/svg plugin to be present at runtime.

I'll work on an example solution.

**Comment by mark-summerfield** [comment]
Thank you.

**Comment by mappu** [comment]
@mark-summerfield I tried your code today and the SVG rendering worked perfectly with no code changes.

With `go-up.png`:

![image](https://github.com/user-attachments/assets/2c3eecc5-6138-47f4-913d-8c562b67c171)

With `go-up.svg`:

![image](https://github.com/user-attachments/assets/3318edf3-05e1-4583-b3c6-9e8c76333601)

I think, you are just missing Qt SVG installed on your system.

Can you try `apt install libqt5svg5` (Qt 5) or `apt install libqt6svg6` (Qt 6) and check if it's solved?

**Comment by mark-summerfield** [comment]
Yes, you are quite right, once I installed libqt6svg6 it worked perfectly.
Thank you.
