### ISSUE TITLE
Call runtime.LockOSThread automatically in NewQApplication

### ISSUE THREAD

**Issue by mappu** [mappu/miqt#72]
> Wow. Indeed, calling runtime.LockOSThread() before NewQApplication seems to make it always work.

_Originally posted by @ilius in https://github.com/mappu/miqt/discussions/68#discussioncomment-11202894_

**Comment by ilius** [comment]
Although if `NewQApplication` itself is called in another function which is called in `main()`, this may not fix the problem (I had that issue in FreeBSD).
I think `runtime.LockOSThread()` should be called directly inside `main()`.

**Comment by mappu** [comment]
@ilius Are you sure?

The documentation for LockOSThread says it should affect the entire goroutine indefinitely. It doesn't stop taking effect when returning from the function, it only stops taking effect when explicitly unlocking with UnlockOSThread.

But, real experience beats documentation.

Sorry to bother you but since I can't currently reproduce this, would you be able to remove your own calls to LockOSThread and try the branch from #83 ?

**Comment by ilius** [comment]
I got this error with #84
https://gist.github.com/ilius/48a96df3d4acd5cb06757f77dcbb7ceb

Then I ran `sudo rm -rf $GOPATH/pkg/mod/github.com/mappu/miqt\@v0.*` and `go build` again, but it finished quickly.
So I ran `rm -rf ~/.cache/go-build/` and `go build` again, and I got the same error as above.

**Comment by ilius** [comment]
I get this error on `master` as well.
I might have updated my Qt since last build.
How to fix it?

**Comment by mappu** [comment]
> Cannot mix incompatible Qt library (6.7.3) with this library (6.7.2)

I think this is caused by a mismatched version of your qt6 and qt6-multimedia packages. Really they should have the same version. Can you check in your package manager if there are more updates?

**Comment by ilius** [comment]
They are both 6.7.3, the latest version.

**Comment by ilius** [comment]
FreeBSD's pkg is not as clever as Linux's apt or dnf I guess!

**Comment by ilius** [comment]
Moving `runtime.LockOSThread` out of `main()` func to before `qt.NewQMainWindow` works now.
Maybe I was doing something wrong before!

Also #83 without `runtime.LockOSThread` works.

Next I removed `runtime.LockOSThread` and reverted back miqt to master, compiled and ran, this time with no error! But the app window does not show up! Did they change something in Qt 4.7.3 that caused this (it sounds worse!).

Anyway, #83 fixes it.

**Comment by mappu** [comment]
Thank you @ilius for the extra testing. It is difficult to reproduce this intermittent issue, so I'm really glad to hear that #83 solved the issue for you.
