### ISSUE TITLE
can't build simple hello world anymore

### ISSUE THREAD

**Issue by mark-summerfield** [mappu/miqt#87]
I am getting this error message:
```
$ go run .
go: downloading github.com/mappu/miqt v0.6.0
# github.com/mappu/miqt/qt6
# [pkg-config --cflags  -- Qt6Widgets]
Package Qt6Widgets was not found in the pkg-config search path.
Perhaps you should add the directory containing `Qt6Widgets.pc'
to the PKG_CONFIG_PATH environment variable
No package 'Qt6Widgets' found
```
I had already installed `qt6-base-dev` and `build-essential` and `libqt6widgets6`.

**Comment by mark-summerfield** [comment]
I made a mistake this isn't valid.

**Comment by lescuer97** [comment]
@mark-summerfield I'm getting this problem. how did you solve this?

**Comment by rcalixte** [comment]
> [@mark-summerfield](https://github.com/mark-summerfield) I'm getting this problem. how did you solve this?

Did you install all of the required dependencies? If you are getting the same message, make sure to compare with the README or just copy and paste to be sure.

**Comment by mappu** [comment]
The problem is that `Qt6Widgets.pc` was not found in the path listed in the `PKG_CONFIG_PATH` environment variable.

- What is the `PKG_CONFIG_PATH` environment variable set to?
- Where is your `Qt6Widgets.pc` file? It should be inside the Qt installation directory.

**Comment by lescuer97** [comment]
> * pkg-config --variable pc_path pkg-config

it shows up as empty, I ran the command you send and it shows this:

/usr/local/lib/x86_64-linux-gnu/pkgconfig:/usr/local/lib/pkgconfig:/usr/local/share/pkgconfig:/usr/lib/x86_64-linux-gnu/pkgconfig:/usr/lib/pkgconfig:/usr/share/pkgconfig

> Where is your Qt6Widgets.pc file? It should be somewhere within the Qt installation directory

I actually can't find it. I did run the full command for ubuntu installation.

Command: 
```
sudo nala install qt6-base-dev libqscintilla2-qt6-dev qt6-base-private-dev qt6-charts-dev qt6-multimedia-dev qt6-pdf-dev qt6-svg-dev qt6-webchannel-dev qt6-webengine-dev qt6-declarative-dev qml6-module-qtquick-{controls,shapes,layouts,templates,window} build-essential golang-go
[sudo] password for leo:
build-essential is already at the latest version 12.9ubuntu3
qt6-base-dev is already at the latest version 6.2.4+dfsg-2ubuntu1.1
Error: libqscintilla2-qt6-dev not found
Error: qt6-charts-dev not found
Error: qt6-svg-dev not found
Error: qt6-webchannel-dev not found
```

**Comment by rcalixte** [comment]
> I actually can't find it. I did run the full command for ubuntu installation.

You're running Ubuntu 22.04 which doesn't have many of the extra modules packaged. They are there in Ubuntu 24.04 though. The README also says that Qt 6.4+ is supported and Ubuntu 22.04 ships Qt 6.2.

**Comment by lescuer97** [comment]
> > I actually can't find it. I did run the full command for ubuntu installation.
> 
> You're running Ubuntu 22.04 which doesn't have many of the extra modules packaged. They are there in Ubuntu 24.04 though. The README also says that Qt 6.4+ is supported and Ubuntu 22.04 ships Qt 6.2.

I need to stay in ubuntu 22 for a while now. How could I solve this issue?

**Comment by rcalixte** [comment]
> I need to stay in ubuntu 22 for a while now. How could I solve this issue?

Have you looked into some of the Docker options here?
