### ISSUE TITLE
The filename or extension is too long on the windows

### ISSUE THREAD

**Issue by StinkyPeach** [mappu/miqt#99]
go: 1.20.14
qt: 5.15 Qt5.15.14-Windows-x86_64-llvm-mingw-16.0.6-msvcrt-20240528
pkg-config: pkg-config-lite-0.28-1_bin-win32
llvm-mingw: llvm-mingw-20230614-msvcrt-x86_64

windows longpath enabled
![image](https://github.com/user-attachments/assets/db7f3aa4-e46a-4728-830e-dca7ecbb26d3)

build miqt/examples/helloworld failed.

build command:
CGO_CXXFLAGS="-Wno-ignored-attributes -D_Bool=bool" CGO_ENABLED=1 CC="C:\llvm-mingw\bin\clang.exe" CXX="C:\llvm-mingw\bin\clang++.exe" PKG_CONFIG_PATH="C:\Qt5.15.14\lib\pkgconfig" go build -x -v github.com/mappu/miqt/examples/helloworld

![image](https://github.com/user-attachments/assets/a67e185e-8419-4eeb-a274-f5a8963a426f)

**Comment by rcalixte** [comment]
Have you had a chance to try this with a newer (and supported) version of Go? It's possible that this is an upstream bug that has already been resolved.

**Comment by StinkyPeach** [comment]
> Have you had a chance to try this with a newer (and supported) version of Go? It's possible that this is an upstream bug that has already been resolved.

Thank you, I can compile successfully using go1.21 or later versions.
